import Head from "next/head";
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube }
 from 'react-icons/ai';


 import Image from "next/image";
 import deved from "../public/images/dev-ed-wave.png";
 import design from "../public/images/design.png";
 import code from "../public/images/code.png";
 import consult from "../public/images/consulting.png";
 import web1 from "../public/images/web1.png"
 import web2 from "../public/images/web2.png"
 import web3 from "../public/images/web3.png"
 import web4 from "../public/images/web4.png"
 import web5 from "../public/images/web5.png"
 import web6 from "../public/images/web6.png"
 import { useState } from "react";





export default function Home() {
  const[darkMode,setDarkMode]= useState(false);
  return (
    <div className={darkMode ? "dark": ""} >
      <Head>
        <title >My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-7 bg-slate-200 dark:bg-gradient-to-br from-cyan-600 via-sky-200 to-cyan-300
       md:pb-28 pb-10  dark:text-slate-900  md:px-20 lg:px-40 ">
        <section className=" min-h-screen">

          <nav className=" md:p-8 p-7 md:mb-7 mb-5 justify-between flex">
            <h1 className="sm:text-2xl text-xl text-blue-600 dark:text-black  font-bold ">PortfolioSite</h1>
            <ul className="flex items-center">
                <li>
                <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className="
                dark:text-white cursor-pointer text-2xl " />
                 </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500
                   text-white px-2 py-1 md:py-2 md:px-4 border-none rounded-md md:ml-6 ml-3"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>


          <div className="text-center  ">
            <h2 className="text-red-600 dark:text-blue-700 text-5xl font-medium ">JubairAhmed</h2>
            <h2 className=" uppercase font-bold py-2">Devoleper & Designer </h2>

            <p className="text-gray-700 leading-7 py-3 mx-auto text-md">A software development engineer applies the
             principles of computer science, information technology and <br></br> 
             computer engineering to generate applications and software.
            </p>
          </div>
          
          <div className="flex justify-center text-red-600  dark:text-black text-4xl md:text-4xl gap-7">
              <AiFillLinkedin  />
              <AiFillYoutube />
              <AiFillTwitterCircle />
          </div>
          <div className="relative mx-auto
           bg-gradient-to-b from-cyan-500 rounded-full to-blue-900
          md:w-96 md:h-96  w-80 h-80 mt-5 overflow-hidden shadow-2xl">
            <Image src={deved}  layout="fill" objectFit="cover" overfl/>
          </div>
      </section>

       

        <section>


          <div>
            <h3 className="text-3xl py-2 font-bold">Services I Offer</h3>
            <p className=" capitalize leading-6 py-2 ">
                I am working as a software Devoleper in <span className="text-red-600 dark:text-blue-600 font-bold">GOOGLE </span>
                 from the last Few years. we Provide Offers in
                  lowest Possible Prices
                 feel Free To Dm Us :() 
            </p>
            <p className=" capitalize leading-6 py-2 ">
                A software development engineer applies the princ
              iples of computer science, information technology, and computer engineering to generate applications and software. They analyze to assist businesses and individuals in making wise 
              decisions.
               <br/>
              I am working as a software Devoleper in Google.......
              <br/>
              <span className="text-cyan-800 text-3xl font-bold">"Google Boltheyy"</span>
            </p>
          </div>





          <div className="flex lg:flex-row md:mx-5  md:gap-0 md:space-x-8 flex-col-reverse">


            {/* 1------------- */}
               <div className="md:my-14 my-4 text-center p-5 shadow-2xl  rounded-xl">
               <Image src={design}  width={100} height={100} />
               <h3 className="text-lg font-medium pb-4">Beauiful Designs</h3>
               <p className=" capitalize leading-6 py-2 ">
                I am working as a software Devoleper in <span className="text-cyan-800 font-bold">GOOGLE </span>
                 from the last Few years. we Provide Offers in
                  lowest Possible Prices
                 feel Free To Dm Us :() 
               </p>
               <h4 className="py-3 text-blue-600 font-bold"> design Tools I Used </h4>
               <p className="py-1 to-gray-300">Photoshop</p>
               <p className="py-1 to-gray-300">DiIllustrator</p>
               <p className="py-1 to-gray-300">Photoshop Adobe</p>
               
              {/* 2---------------   */}
               </div>
               <div className="md:my-14 text-center p-5 shadow-xl  rounded-xl">
               <Image src={code}  width={100} height={100} />
               <h3 className="text-lg font-medium pb-4">Beauiful Designs</h3>
               <p className=" capitalize leading-6 py-2 ">
                I am working as a software Devoleper in <span className="text-cyan-800 font-bold">GOOGLE </span>
                 from the last Few years. we Provide Offers in
                  lowest Possible Prices
                 feel Free To Dm Us :()
               </p>
               <h4 className="py-3 text-blue-600 font-bold"> design Tools I Used </h4>
               <p className="py-1 to-gray-300">Photoshop</p>
               <p className="py-1 to-gray-300">DiIllustrator</p>
               <p className="py-1 to-gray-300">Photoshop Adobe</p>
              
               </div>

               {/* 3------- */}
               <div className="md:my-14 text-center p-5 shadow-xl  rounded-xl">
               <Image src={consult}  width={100} height={100} />
               <h3 className="text-lg font-medium pb-4">Beauiful Designs</h3>
               <p className=" capitalize leading-6 py-2 ">
                I am working as a software Devoleper in <span className="text-cyan-800 font-bold">GOOGLE </span>
                 from the last Few years.
                  we Provide Offers in
                  lowest Possible Prices
                 feel Free To Dm Us :()
               </p>
               <h4 className="py-3 text-blue-600 font-bold"> design Tools I Used </h4>
               <p className="py-1 to-gray-300">Photoshop</p>
               <p className="py-1 to-gray-300">DiIllustrator</p>
               <p className="py-1 to-gray-300">Photoshop Adobe</p> 
               </div>

          </div>
        </section>



        <section>
          <div>

          <h3 className="text-3xl py-3 md:my-5 ">Portfolio</h3>
           
          <p className="text-gray-700 leading-7 py-4 text-md">
          I am working as a software Devoleper in <span className="text-cyan-800 font-bold">GOOGLE </span>
          <br></br>
          Learn New Skills For Better Carrier Options  <br></br>
          A software development engineer applies the princ
              iples of computer science, information technology, and computer engineering to generate applications and software. They analyze to assist businesses and individuals in making wise 
              decisions.</p>
          </div>
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap " >
            <div className="basis-1/3 flex-1 " >
              <Image src={web1}  className="rounded-lg object-cover 
              " width={'100%'} height={'100%'} 
                layout="responsive"  />
            </div>
            <div className="basis-1/3 flex-1 " >
              <Image src={web2} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1 " >
              <Image src={web3} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1 " >
              <Image src={web4} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1 " >
              <Image src={web5} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1 " >
              <Image src={web6} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>

         

       </main>
       
       <footer className="md:pt-7 shadow-3xl bg-slate-300  dark:bg-cyan-600">
          <div className="p-2">
            <h3 className=" dark:text-white  md:text-2xl text-red-600 dark:text-decoration-pink-600
             font-bold text-l text-center my-10 "> 亗亗亗 Shaik Jubair Ahmed 亗亗亗  </h3>
          </div>
        </footer>
      
    </div>
  );
};
